naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'

build:
  maxIssues: 0

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 120

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
  TooManyFunctions:
    active: false
